name: google sheet update

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install dependencies and run script
        run: |
          python -m pip install --upgrade pip
          pip install pipenv 
          pipenv install
          pipenv run python src/update_google_sheet.py

